#!/usr/bin/env bash
# install Nginx on the server

# sudo apt-get install nginx
# ufw allow 'Nginx HTTP'
# sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
# #sudo systemctl reload nginx
# sudo apt-get install -y nginx


sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
