#!/usr/bin/env bash
# configure a new Ubuntu machine

sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
# enable nginx to ensure it starts automatically on boot
sudo systemctl enable nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
#sudo sed -i '/server_name _;/a\ \ \ \ \ \ \ \ add_header X-Served-By $hostname;' /etc/nginx/sites-enabled/default
sudo sed -i '/server_name _;/a\ \ \ \ \ \ \ \ add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

#sudo find /etc/nginx/sites-available/ -type f -exec ln -s {} /etc/nginx/sites-enabled/ \;

sudo systemctl reload nginx
