#!/usr/bin/env bash
# install and configure HAproxy load balancer
sudo apt update

# Install HAProxy
sudo apt install -y haproxy

# Configure HAProxy
echo "global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 466719-web-01 54.158.193.232 check
    server 466719-web-02 54.165.175.218 check
" | sudo tee /etc/haproxy/haproxy.cfg

# Enable and start HAProxy
sudo systemctl enable haproxy
sudo systemctl start haproxy

# to make sure the setup completed correctly
echo "HAProxy has been installed and configured."
