#!/usr/bin/env bash
# install Nginx on the server

sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
# enable nginx to ensure it starts automatically on boot
sudo systemctl enable nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo systemctl reload nginx
