#!/usr/bin/env bash
#transfer a file from our client to a server

if [ $# -lt 4 ];
    then
        echo "Usage: transfer_files PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit 1

else
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$2@$3:~/"

fi
