#!/usr/bin/env bash
#the Fizz Buzz game in bash
num=1
while [ $num -le 100 ];
do
case $num in

*)
if ((num % 3 == 0)) && ((num % 5 == 0))
    then
    echo "FizzBuzz"

elif (( num %  3 ==  0 ));
    then
    echo "Fizz"

elif (( num %  5 ==  0 ));
    then
    echo "Buzz"

else
echo $num

fi
;;

esac

# if [ $((num % 3)) ] && [ $((num % 5)) ];
# then
# echo "FizzBuzz"

# elif [ $((num % 3)) ];
# then
# echo "Fizz"

# elif [ $((num % 5)) ];
# then
# echo "Buzz"

# else
# echo $num

# fi

((num += 1))
done