#!/usr/bin/env bash
#change the home ip

###sudo cp /etc/hosts /etc/hosts.old
echo "127.0.0.2 localhost" | sudo tee /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

# echo "127.0.0.2 localhost" | sudo tee --output-error 'exit' /etc/hosts
# echo "8.8.8.8 facebook.com" | sudo tee --output-error 'exit' /etc/hosts
###cat /etc/hosts.old
#cat /etc/hosts